jQuery.fn.exists=function(){return 0<jQuery(this).length};
function applicationInitialize(){function m(){require("dojo/_base/array dojo/_base/lang dojo/dom-construct dojo/on dojo/parser dojo/query!css3 esri/Color esri/config esri/dijit/AttributeInspector esri/dijit/Scalebar esri/dijit/Geocoder esri/dijit/HomeButton esri/dijit/LocateButton esri/dijit/PopupMobile esri/geometry/webMercatorUtils esri/graphic esri/InfoTemplate esri/layers/FeatureLayer esri/map esri/symbols/SimpleLineSymbol esri/symbols/SimpleMarkerSymbol esri/tasks/locator esri/tasks/query dojo/domReady!".split(" "),function(g,
n,h,c,k,m,y,R,p,z,A,B,C,D,E,F,G,q,H,r,f,I,J){function K(a){var e=null;$.each(b.carp8Layer.types,function(b,d){d.name===a&&(e=d.templates[0])});return e}function M(a){$("#ui-collection-prompt").popup("open");var e=K(a),L=c(b.map,"click",function(a){L.remove();b.collectMode=!1;var c=new Date,t=n.mixin({},e.prototype.attributes);t.requestdate=Date.UTC(c.getUTCFullYear(),c.getUTCMonth(),c.getUTCDate(),c.getUTCHours(),c.getUTCMinutes(),c.getUTCSeconds(),0);a=new F(a.mapPoint,null,t);b.carp8Layer.applyEdits([a],
null,null,function(a){var e=new J;e.objectIds=[a[0].objectId];b.carp8Layer.queryFeatures(e,function(a){0<a.features.length?(a=E.webMercatorToGeographic(a.features[0].geometry),b.locator.locationToAddress(a,100,function(a){var b=[];a.address?(a.address.Address&&b.push(a.address.Address),a.address.City&&b.push(a.address.City+","),a.address.Region&&b.push(a.address.Region),a.address.Postal&&b.push(a.address.Postal),a=b.join(" ")):a="No address for this location";$.mobile.changePage("#ui-attributes-page",
null,!0,!0);$("#currentAddress")[0].textContent=a},function(a){console.warn("Unable to find address, maybe there are no streets at this location",a.details[0]);$.mobile.changePage("#ui-attributes-page",null,!0,!0);$("#currentAddress")[0].textContent=a.details[0]})):console.warn("Unable to locate the feature that was just collected.")})},function(a){console.error(JSON.stringify(a))})})}function N(a){$.each(a.layers,function(a,c){var d=c.layer;d.hasOwnProperty("renderer")&&(d=d.renderer,d.hasOwnProperty("infos")&&
(d=d.infos,$("#ui-feature-list").append('<li data-role="list-divider" class="ui-li-divider ui-bar-inherit ui-first-child">Tag a sighting</li>'),$.each(d,function(a,e){l[e.value]=e.label;var c=$("<li/>").on("click",function(a){b.map.setMapCursor("pointer");M(e.label);b.collectMode=!0});c.attr("data-theme","a");var d=[];d.push('<a href="#ui-map-page" class="ui-btn ui-btn-icon-right ui-icon-plus">'+e.label+"</a>");c.append(d.join(""));$("#ui-feature-list").append(c)})))})}k.parse();k=new r(r.STYLE_SOLID,
new y([38,38,38,.7]),2);f=new f;f.setPath("M21.5,21.5h-18v-18h18V21.5z M12.5,3V0 M12.5,25v-3 M25,12.5h-3M3,12.5H0");f.setSize(45);f.setOutline(k);var u=new D({markerSymbol:f},h.create("div")),l={},v={};h=new G;h.setTitle("<center><b>${Name}</b></center>");h.setContent("<b>Common Name: </b>${Name}<br/><b>Genus: </b>${severity:severityDomainLookup}<br/><b>Species: </b>${requesttype:requestTypeDomainLookup}<br/><b>Date: </b>${Date:DateFormat}<br><b>Verified on: </b>${Verified:DateFormat}<br><b>Water Temperature: </b> ${Water_temp}&deg;C<br><b>Weight: </b> ${Weight} grams<br><b>Length: </b> ${Length} millimeters<br><b>Comments: </b> ${Comments}");
severityDomainLookup=function(a,b,c){return l[a]};requestTypeDomainLookup=function(a,b,c){return v[a]};b.map=new H("ui-map",{sliderOrientation:"horizontal",sliderPosition:"bottom-right",basemap:"topo",center:b.center,zoom:7,sliderStyle:"small",infoWindow:u});b.locator=new I(b.locatorURL);new z({map:b.map,scalebarUnit:"english",attachTo:"bottom-left"});var O=new A({arcgisGeocoder:{placeholder:"Search "},map:b.map},"ui-dijit-geocoder"),w=new C({map:b.map},"ui-dijit-locatebutton"),x=new B({map:b.map},
"ui-home-button-hidden");b.carp8Layer=new q(b.carp8LayerURL,{mode:q.MODE_ONEDEMAND,infoTemplate:h,outFields:["*"]});var P=new p({layerInfos:[{featureLayer:b.carp8Layer,showAttachments:!0,showDeleteButton:!1,isEditable:!0,fieldInfos:[{fieldName:"Name",label:"Name",isEditable:!0},{fieldName:"severity",label:"Genus",isEditable:!0},{fieldName:"requesttype",label:"Species",isEditable:!0},{fieldName:"Date",label:"Date",isEditable:!0},{fieldName:"Verified",label:"Verified",isEditable:!0},{fieldName:"Water_temp",
label:"Water temp (&deg;C)",isEditable:!0},{fieldName:"Weight",label:"Weight (g)",isEditable:!0,visible:!0},{fieldName:"Length",label:"Length (mm)",isEditable:!0,visible:!0},{fieldName:"Comments",label:"Comments",isEditable:!0,stringFieldOption:p.STRING_FIELD_OPTION_TEXTAREA}]}]},"ui-attributes-container");(function(){c(b.map,"load",function(a){b.map.infoWindow.resize(185,100);c(b.map,"layers-add-result",N)});c(b.carp8Layer,"error",function(a){console.error("carp8Layer failed to load.",JSON.stringify(a.error));
$(".ui-loader").hide()});c(b.carp8Layer,"load",function(a){b.carp8Layer.hasOwnProperty("fields")?g.forEach(b.carp8Layer.fields,function(a,b){"severity"===a.name&&a.hasOwnProperty("domain")&&a.domain.hasOwnProperty("codedValues")&&g.forEach(a.domain.codedValues,function(a){l[a.code]=a.name});"requesttype"===a.name&&a.hasOwnProperty("domain")&&a.domain.hasOwnProperty("codedValues")&&g.forEach(a.domain.codedValues,function(a){v[a.code]=a.name})}):console.error("Unable to find property fields in: ",JSON.stringify(b.carp8Layer));
$(".ui-loader").hide()});c(b.carp8Layer,"click",function(a){b.map.infoWindow.setFeatures([a.graphic])});c(P,"attribute-change",function(a){var b=a.feature;a.fieldName&&a.fieldValue&&(b.attributes[a.fieldName]=a.fieldValue);b.getLayer().applyEdits(null,[b],null)});c(w,"locate",function(a){});c(u,"show",function(a){$("*.esriMobileNavigationItem.left > img[src]").exists()&&$("*.esriMobileNavigationItem.left > img").removeAttr("src");$("*.esriMobileNavigationItem.right > img[src]").exists&&$("*.esriMobileNavigationItem.right > img").removeAttr("src")});
O.startup();w.startup();x.startup();$("#ui-home-button").click(function(){x.home();$("#ui-settings-panel").panel("close")});$(".basemapOption").click(Q);$("#ui-features-panel").on("popupafteropen",function(a,c){$("#ui-features-panel").on("popupafterclose",function(a,c){b.collectMode?$("#ui-collection-prompt").show():$("#ui-collection-prompt").hide();setTimeout(function(){$("#ui-collection-prompt").popup("open")},15)})});$("#ui-collection-prompt").on("popupafteropen",function(a,b){setTimeout(function(){$("#ui-collection-prompt").popup("close")},
1200)})})();b.map.addLayers([b.carp8Layer])})}function Q(g){b.map.setBasemap(g.target.dataset.basemapname);$("#ui-settings-panel").panel("close")}var b={map:null,collectMode:!1,carp8Layer:null,locator:null,locatorURL:"https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer",carp8LayerURL:"https://gis14.uwec.edu/arcgis/rest/services/leiferdj/carp8/FeatureServer/0",center:[-90.145746,37.978284]};$.mobile.pagecontainer({defaults:!0});$.mobile.pagecontainer({create:function(b,n){$(".ui-loader").show();
m()}})}$(function(){applicationInitialize()});